// Generated by https://quicktype.io
//
// To change quicktype's target language, run command:
//
//   "Set quicktype target language"

export type FlightOfferSearchResponse = {
  data: FlightOffer[];
}

export type FlightOffer = {
  type:                     string;
  id:                       string;
  source:                   string;
  instantTicketingRequired: boolean;
  nonHomogeneous:           boolean;
  oneWay:                   boolean;
  lastTicketingDate:        string;
  numberOfBookableSeats:    number;
  itineraries:              Itinerary[];
  price:                    DatumPrice;
  pricingOptions:           PricingOptions;
  validatingAirlineCodes:   string[];
  travelerPricings:         TravelerPricing[];
}

export type Itinerary = {
  duration: string;
  segments: Segment[];
}

export type Segment = {
  departure:       Arrival;
  arrival:         Arrival;
  carrierCode:     string;
  number:          string;
  aircraft:        Aircraft;
  operating:       Operating;
  duration:        string;
  id:              string;
  numberOfStops:   number;
  blacklistedInEU: boolean;
}

export type Aircraft = {
  code: string;
}

export type Arrival = {
  iataCode: string;
  at:       string;
}

export type Operating = {
  carrierCode: string;
}

export type DatumPrice = {
  currency:   Currency;
  total:      string;
  base:       string;
  fees:       Fee[];
  grandTotal: string;
}

export enum Currency {
  Brl = "BRL",
}

export type Fee = {
  amount: string;
  type:   string;
}

export type PricingOptions = {
  fareType:                string[];
  includedCheckedBagsOnly: boolean;
}

export type TravelerPricing = {
  travelerId:           string;
  fareOption:           FareOption;
  travelerType:         TravelerType;
  price:                TravelerPricingPrice;
  fareDetailsBySegment: FareDetailsBySegment[];
  associatedAdultId?:   string;
}

export type FareDetailsBySegment = {
  segmentId:            string;
  cabin:                Cabin;
  fareBasis:            FareBasis;
  brandedFare:          BrandedFare;
  class:                Class;
  includedCheckedBags?: IncludedCheckedBags;
}

export enum BrandedFare {
  Azul = "AZUL",
}

export enum Cabin {
  Economy = "ECONOMY",
}

export enum Class {
  F = "F",
  G = "G",
}

export enum FareBasis {
  Feebfz4L = "FEEBFZ4L",
  Glebfz4L = "GLEBFZ4L",
}

export type IncludedCheckedBags = {
  quantity: number;
}

export enum FareOption {
  Standard = "STANDARD",
}

export type TravelerPricingPrice = {
  currency: Currency;
  total:    string;
  base:     string;
}

export enum TravelerType {
  Adult = "ADULT",
  Child = "CHILD",
  HeldInfant = "HELD_INFANT",
}
