// Generated by https://quicktype.io
//
// To change quicktype's target language, run command:
//
//   "Set quicktype target language"

export type HotelOfferSearchResponse = {
  data: HotelOffer[];
}

export type HotelOffer = {
  type:      string;
  hotel:     Hotel;
  available: boolean;
  offers:    Offer[];
  self:      string;
}

export type Hotel = {
  type:          string;
  hotelId:       string;
  chainCode:     string;
  dupeId:        string;
  name:          string;
  rating:        string;
  cityCode:      string;
  latitude:      number;
  longitude:     number;
  hotelDistance: HotelDistance;
  address:       Address;
  contact:       Contact;
  description:   Description;
}

export type Address = {
  lines:       string[];
  postalCode:  string;
  cityName:    string;
  countryCode: string;
  stateCode:   string;
}

export type Contact = {
  phone: string;
  fax:   string;
  email: string;
}

export type Description = {
  lang: string;
  text: string;
}

export type HotelDistance = {
  distance:     number;
  distanceUnit: string;
}

export type Offer = {
  id:           string;
  checkInDate:  string;
  checkOutDate: string;
  rateCode:     string;
  commission:   Commission;
  room:         Room;
  guests:       Guests;
  price:        Price;
  policies:     Policies;
  self:         string;
}

export type Commission = {
  percentage: string;
}

export type Guests = {
  adults: number;
}

export type Policies = {
  paymentType:  string;
  cancellation: Cancellation;
}

export type Cancellation = {
  deadline: string;
}

export type Price = {
  currency: string;
  base:     string;
  total:    string;
  taxes:    Tax[];
}

export type Tax = {
  code:     string;
  amount:   string;
  currency: string;
  included: boolean;
}

export type Room = {
  type:          string;
  typeEstimated: TypeEstimated;
  description:   Description;
}

export type TypeEstimated = {
  category: string;
  beds:     number;
  bedType:  string;
}
